# Generated by Django 4.2.6 on 2023-10-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contact_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('middlename', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('customermobile1', models.IntegerField(max_length=12)),
                ('alternatenumber', models.IntegerField(max_length=12)),
                ('customeraddress', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=150)),
                ('shpdescription', models.CharField(max_length=122)),
                ('shopaddress', models.CharField(max_length=150)),
                ('shopphone', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=122)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productdescription', models.CharField(max_length=122)),
                ('quantity', models.IntegerField(max_length=3)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('price', models.ManyToManyField(blank=True, related_name='order', to='myapp.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
