# Generated by Django 4.2.6 on 2023-10-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_shop_product_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternatenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customermobile1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopphone',
            field=models.IntegerField(),
        ),
    ]
