# Generated by Django 4.2.6 on 2023-10-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customer_alternatenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shpdescription',
            new_name='shopdescription',
        ),
    ]
