# Generated by Django 4.2.6 on 2023-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_shpdescription_shop_shopdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternatenumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middlename',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
