# Generated by Django 4.2.6 on 2023-10-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customer_alternatenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alternatenumber',
        ),
    ]
