# Generated by Django 4.2.6 on 2023-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_quantity_ordermodel_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='order', to='myapp.product'),
        ),
    ]
