# Generated by Django 4.2.6 on 2023-10-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_ordermodel_price_remove_ordermodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
