# Generated by Django 4.2.6 on 2023-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_ordermodel_price_remove_ordermodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
