# Generated by Django 4.2.6 on 2023-10-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_ordermodel_quantity_remove_ordermodel_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=150)),
                ('drivercontact', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverystatus', models.CharField(max_length=122)),
                ('paymentstatus', models.CharField(max_length=122)),
                ('paymentmethod', models.CharField(max_length=122)),
                ('deliveryagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
            ],
        ),
    ]
