# Generated by Django 4.2.6 on 2023-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='billamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
