# Generated by Django 4.2.6 on 2023-10-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delivery_billamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='billamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveryagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliverystatus',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermodel'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='paymentmethod',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='paymentstatus',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
    ]
