# Generated by Django 4.2.6 on 2023-10-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_delivery_billamount_alter_delivery_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='shop',
        ),
    ]
